### ISSUE TITLE
rw_reg.py status

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#1]
Is ```rw_reg.py``` up-to-date with the latest in [GEM_AMC](https://github.com/evka85/GEM_AMC)
I know there were some updates when the address tables were adjusted, and you made some in your version.
We should strive to make sure that these files are the same, probably, and only modified in one repository

**Comment by mexanick** [comment]
I'm actually working on resolving these repository uncertainties. The GEM_AMC repository will stay only for FW purposes and all the software stuff will be removed from there. I just have to make sure that nothing will be lost and Evaldas will update the GEM_AMC. But even now as a rule of thumb, you should not use anything from GEM_AMC/ctp7/apps

**Comment by jsturdy** [comment]
Not from ```GEM_AMC/ctp7/apps```, rather from ```GEM_AMC/scripts/rw_reg.py```
In fact, if this file is in *three* places, it should *definitely* be cleaned up
Remove duplication!!! :)

**Comment by mexanick** [comment]
WTF! I even didn't know it exists there! Will take a look

Am I right that the only changes you've made to rw_reg.py is an ability to parse a given number of OHs? I.e. 3 instead of 12?

**Comment by mexanick** [comment]
I've sent an invite to Evaldas to join this communication. This script is used in his FW to generate address tables (it's parsing XML part only). If we want to have it in only one location, we have to communicate with him. He should join us here shortly
