### ISSUE TITLE
Feature Request: readKW for Link X

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#10]
## Brief summary of issue

Right now the `readKW` functionality is very useful and allows reading registers matching keyword from all links.  Would like to request that this be expanded to allow reading a keyword for just a specific link, e.g. for reading `VThreshold1` from all VFATs on link 0 you could execute:

```
readKW VThreshold1 0
```

Or more generally:

```
readKW <keyword> <link #>
```

And then be given the output.  If no link number is specified then it defaults to current behavior where all links are displayed.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

See syntax example above.

## Current Behavior

Right now the `readKW` functionality just queries all links, which may present a large wall of text to the user, and they may only be interested in a specific link.

## Context (for feature requests)

Quality of life improvement.

**Comment by mexanick** [comment]
@bdorney same comment as to Jared in #11 : next time when you create an issue please either mention or assign it to developers. I didn't receive a notification for this issue and found it just by chance...
