### ISSUE TITLE
Unable to cancel request in reg_interface

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#11]
## Brief summary of issue
Sometimes, one types a command and wants to quit before 12 OH links information is printed.
Pressing `ctrl+c` will quit `reg_interface`

### Types of issue

- [x] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior
Typing `ctrl+c` or something equivalent will stop printing to the screen the remaining messages (on the host PC this printing is rather slow)

## Current Behavior
`ctrl+c` kills `reg_interface`

### Steps to Reproduce (for bugs)
1. start `reg_interface`
2. type `readKW GEM_AMC.DAQ`
3. see the interesting stuff at the top and then realize that you don't care about the link specific stuff
4. press `ctrl+c`
5. cry

## Possible Solution (for bugs)
* Cross session command history could be considered a "workaround"

**Comment by mexanick** [comment]
@jsturdy next time when you create an issue please either mention or assign it to developers. I didn't receive a notification for this issue and found it just be chance...
