### ISSUE TITLE
Call wrapper for SCA ADC functionality

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/xhal#122]
## Brief summary of issue

Need to implement the RPC call wrapper to use the recently added SCA ADC methods of ctp7_modules, in particular for the temperature readings. Target branch: `legacyPreBoost`
### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Read and return the ADC values for various sensors embedded on the GEM front-end electronics
## Current Behavior

None

**Comment by lpetre-ulb** [comment]
Will this feature be ever implemented in the legacy branch? I'd say no.
