### ISSUE TITLE
Two versions of `memhub` exist

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/xhal#127]
## Brief summary of issue

While working on https://github.com/cms-gem-daq-project/xhal/issues/126 I noticed that two version of `memhub` exist. One in `xhal/xcompile` which does not use the `LOGGER` and is named `libmemhub.so`, the other one in the `ctp7_modules` which uses the `LOGGER` and is named `memhub.so`.

### Types of issue

- [x] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Only one version of `memhub` should exist.

Once and if the `ctp7_module` logging system is converted to `log4cplus` (see this issue https://github.com/cms-gem-daq-project/ctp7_modules/issues/139), my proposal would be to use it in `memhub` and only provide `memhub` once in `xhal`.

At the same time `memhub` could be converted to a complete library which abstracts all calls to `libmemsvc` and provides a class to manage the `memsvc` handle lifetime. The API would also be cleaner if everything is managed by `memhub` instead of `open` and `close` function in `libmemsvc`.

## Current Behavior

Two versions of `memhub` exist.

## Context (for feature requests)

Maintainability and good practices.

**Comment by jsturdy** [comment]
Yes, the initial implementation was here, but was migrated at some point (here it wasn't deleted...)
I would tend to agree, and would try to put all of the GEM agnostic aspects of our register access here in `xhal`, and keep the GEM specific stuff in `ctp7_modules`

In fact, I have been discussing with developers on another upgrade project that what is currently being done with the templating *should* in principle, be usable by any other group using an `rpcsvc` that is similar to the UW client (currently, I think it must be identical), so I think this could be one of our goals for `xhal`, namely that it could be used by another group using either a CTP7, or another board with a similar architecture.

**Comment by lpetre-ulb** [comment]
> Yes, the initial implementation was here, but was migrated at some point (here it wasn't deleted...)

And the two implementations are no longer compatible due to the logging system...

> I would tend to agree, and would try to put all of the GEM agnostic aspects of our register access here in `xhal`, and keep the GEM specific stuff in `ctp7_modules`

If we decide to go that way, the IPBus `libmemsvc` compatibility layer could very well be one of the N (2?) `memhub` backend.
 
> In fact, I have been discussing with developers on another upgrade project that what is currently being done with the templating _should_ in principle, be usable by any other group using an `rpcsvc` that is similar to the UW client (currently, I think it must be identical), so I think this could be one of our goals for `xhal`, namely that it could be used by another group using either a CTP7, or another board with a similar architecture.

I really like the idea of `xhal` becoming a full-featured hardware communication framework with multiple libraries supporting multiple architectures. It will require some (a lot of?) refactoring though.

**Comment by jsturdy** [comment]
> > Yes, the initial implementation was here, but was migrated at some point (here it wasn't deleted...)
> 
> And the two implementations are no longer compatible due to the logging system...

Well, only one of them is actually used (that from `ctp7_modules`)

> > In fact, I have been discussing with developers on another upgrade project that what is currently being done with the templating _should_ in principle, be usable by any other group using an `rpcsvc` that is similar to the UW client (currently, I think it must be identical), so I think this could be one of our goals for `xhal`, namely that it could be used by another group using either a CTP7, or another board with a similar architecture.
> 
> I really like the idea of `xhal` becoming a full-featured hardware communication framework with multiple libraries supporting multiple architectures. It will require some (a lot of?) refactoring though.

To clarify, what I was describing would be simply a generic library that can interface with an RPC service (somehow, a `uhal` "equivalent" for RPC, though the `uhal` guys are working on their own way to leverage embedded processors on back end boards, but that's another thing...)
The main priority for now I think should be that our solution works with current GE1/1 as well as the future ATCA system we (GEM) use for GE2/1.
If we manage to have that requirement met, I think there will be other CMS groups that will be using a similar ATCA back end who could automatically benefit (and encouraging common tooling is usually a good thing :-) )

**Comment by lpetre-ulb** [comment]
> Well, only one of them is actually used (that from `ctp7_modules`)

I think this is not true (or else the [`ipbus` daemon `Makefile`](https://github.com/cms-gem-daq-project/xhal/blob/8863bcc7793b8ea00289b643931b9a5ee2b4c1e1/xcompile/ipbus/Makefile) is terribly outdated). While working on the `ipbus` daemon issue, I had to link to the `libmemhub.so` since 1) we want to avoid concurrent AXI transactions with the RPC modules and 2) the `LOGGER` system is not available for standalone applications.

**Comment by lpetre-ulb** [comment]
Probably never going to be fixed in legacy. Not an issue in the new repository with the new architecture since IPBus is no longer used to communicate with the GEM back-end board.
