### ISSUE TITLE
[feature request] Finalize type (de)serializers

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#138]
## Brief summary of issue
As discussed in cms-gem-daq-project/ctp7_modules#161, there are several missing type (de)serializers.

This is one of the remaining pieces for a released `xhal` in the land of the templated framework.

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Expected Behavior
(de)serializers should be provided for all "common" types

Missing are:
* `std::vector<T>`
* `bool`
* `float`
* `uintX_t` for certain `X` (8 and 16 at least)
* possible `std::unordered_map<K,T>`

**Comment by lmoureaux** [comment]
Just wondering, what's the use case for sending floating-point numbers over the network? I don't think the Wisc RPC API allowed it. Floats are notoriously hard to serialize.

**Comment by jsturdy** [comment]
Currently, there are several CTP7 based methods that do some computation (averaging, etc.) and return that to the caller.
If we can guarantee the same underlying representation, then the stupid reinterpret cast i did in the `ctp7_modules` code could probably work, but in the linked issue (or maybe elsewhere) @lpetre-ulb suggested simply using a string as the transport layer.
I don't a priori have a reason for preferring one over the other, though if the reinterpret cast can be 100% guaranteed, I think it's simpler.
If it is truly only those few functions in some module which are doing this, then probably simply leaving the (de)serialization in that limited scope is probably better

**Comment by lpetre-ulb** [comment]
Indeed, these (de)serializers are in my TODO list. I postponed this development for too long because of the build system; I'll tackle it ASAP (i.e. once the templated RPC work).
