### ISSUE TITLE
Clean-up unused branches

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/xhal#140]
## Brief summary of issue

This repository contains many branches used for past long-lasting developments and quick hot-fixes. I propose to remove all the branches which are no longer useful.

Here is the list of branches I'll delete on Monday except if someone has strong reasons against it. All these branches have been merged in this repository or another GEM repository if the code was moved during refactoring.

* ~`bdorney-patch-1`: References a file which no longer exists in this repository. It has been decided not to merge the PR https://github.com/cms-gem-daq-project/xhal/pull/76~
* ~`hotfix/fix-exceptions`: Merged in https://github.com/cms-gem-daq-project/xhal/pull/101~
* ~`hotfix/legacy-block-nodes`: Merged in https://github.com/cms-gem-daq-project/xhal/pull/107~
* ~`hotfix/simplify-makefiles`: Originally in https://github.com/cms-gem-daq-project/xhal/pull/129, bt then included in https://github.com/cms-gem-daq-project/xhal/pull/125~

Here is the list of branches which I think can safely be deleted, but for which I cannot find the merge commit. Are they still necessary? @mexanick? You created most of them.

* ~`develop-python_package_struct`~: Cannot find the merge commit. Doesn't seem required anymore to package the Python tools.
* ~`mexanick-hotfix-update_atdb`~: Not needed anymore. Python imports work correctly in `python/reg_interface_gem/core/ri_prompt_extended.py`.
* ~`revert-26-feature_rpcOHFunctionality`~: Not sure why we would want to revert the feature since it works and it is used.
* ~`revert-44-feature_currentPulse`~: Not sure why we would want to revert the feature since it works and it is used.

Now, about the active branches:

* ~`feature/templated-rpc-methods`~ has become the development branch and contains the only development in progress. It could be merged into `develop` to simplify the workflow, especially since the two branches already diverged and that the first iteration of the templated code is done.
* ~`legacyPreBoost`~ has technically been renamed `release/legacy-1.0` and should be deleted after developer-wide announcement.

**Comment by jsturdy** [comment]
I would say once `templated-rpc-methods` contains everything needed for a first release of the templated core (minimum #138, but possibly anything else that winds up being necessary re logging/memsvc/etc, but this last part can be part of the releasing) this can be merged to `develop` and then onto `master` and a release created.
Then the usually "all developments start at the current `develop`) would apply again

**Comment by lpetre-ulb** [comment]
The core of the templated RPC is implemented since weeks (months?); it is maybe time to pre-release it (not in `master` then). I consider adding some (de)seriliazers into `develop` as a normal flow. However, if this is the latest remaining feature branch, I won't have a strong opposition against it.

**Comment by lpetre-ulb** [comment]
@mexanick, do you give me the green light to delete the branches listed in the second paragraph? Also, is there any opposition against deleting the `legacyPreBoost` branch (with the appropriate announcement obviously)?

**Comment by mexanick** [comment]
yes, please go ahead
