### ISSUE TITLE
Files copied to the wrong location during local installation

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/xhal#141]
## Brief summary of issue

Installing the most recent `xhal` developments with the updated build system (branch `feature/templated-rpc-methods`) in a local path leads to an unexpected filesystem structure.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

I'm not 100% sure what is the expected behavior, but the local installation seems to be wrong.

## Current Behavior

The paths for the cross-compiled libraries in the local installation folder are highly suspicious, i.e.

``` bash
[lpetre@gem904daq04 local_install]$ tree -L 4
.
├── afs
│   └── cern.ch
│       └── user
│           └── l
├── mnt
│   └── persistent
│       ├── reedmuller
│       │   ├── bin
│       │   ├── etc
│       │   ├── include
│       │   ├── lib
│       │   └── scripts
│       └── xhal
│           ├── bin
│           ├── etc
│           ├── include
│           ├── lib
│           └── scripts
├── opt
│   ├── gem-peta-stage
│   │   └── ctp7
│   │       ├── lib
│   │       └── usr
│   └── xhal
│       ├── bin
│       │   └── reg_interface_gem
│       ├── etc
│       ├── include
│       │   ├── packageinfo.h
│       │   └── xhal
│       ├── lib
│       │   ├── libxhal-base.so -> libxhal-base.so.3.2
│       │   ├── libxhal-base.so.3.2 -> libxhal-base.so.3.2.2
│       │   ├── libxhal-base.so.3.2.2
│       │   ├── libxhal-client.so -> libxhal-client.so.3.2
│       │   ├── libxhal-client.so.3.2 -> libxhal-client.so.3.2.2
│       │   ├── libxhal-client.so.3.2.2
│       │   ├── libxhal-rpcman.so -> libxhal-rpcman.so.3.2
│       │   ├── libxhal-rpcman.so.3.2 -> libxhal-rpcman.so.3.2.2
│       │   ├── libxhal-rpcman.so.3.2.2
│       │   ├── libxhal-server.so -> libxhal-server.so.3.2
│       │   ├── libxhal-server.so.3.2 -> libxhal-server.so.3.2.2
│       │   ├── libxhal-server.so.3.2.2
│       │   ├── xhalpy.so -> xhalpy.so.3.2
│       │   ├── xhalpy.so.3.2 -> xhalpy.so.3.2.2
│       │   └── xhalpy.so.3.2.2
│       └── scripts
└── usr
    ├── lib
    │   ├── debug
    │   │   ├── mnt
    │   │   └── opt
    │   └── python2.7
    │       └── site-packages
    └── src
        └── debug
            ├── reedmuller-..
            └── xhal-3.2.2

42 directories, 16 files
```

Both the `afs` and `mnt` directories contain the `arm` libraries built for the CTP7. Moreover, `mnt` contains the header files for development.

I do not expect an `afs` folder to be created, nor the `mnt` folder to be outside of the `PETA_STAGE` directory.

### Steps to Reproduce (for bugs)

1. Export the `INSTALL_PREFIX` environment variable (e.g. `export INSTALL_PREFIX=/afs/cern.ch/user/l/lpetre/GEM/develop/local_install`)
2. Export the `PETA_PATH` environment variable (e.g. `export PETA_PATH=${INSTALL_PREFIX}/opt/gem-peta-stage`)
3. Build the project: `scl enable devtoolset-8 -- make`
4. Install the project: `scl enable devtoolset-8 -- make install`
5. Look into the local installation directory.

## Context (for feature requests)

Trying to debug the templated RPC code/build/installation.

## Your Environment

* Version used: d465fe56164b435a93af4928f8464e50cbf4294b

**Comment by lpetre-ulb** [comment]
Investigating the issue a little more, it looks like build system cannot currently properly install the files in a local environment:

* The files in `mnt` are those which must be installed on the CTP7. They are not required in a local environment and therefore should not even be installed. This is particularly an issue if two cross-compiled targets use the same directory (e.g. the CTP7 and the GLIB, once ready).
* The files in `afs` are those which must be installed in the sysroot tree. See the source [here](https://github.com/cms-gem-daq-project/gembuild/blob/30f5327e456c26b23a1f6ec224889c5c46610226/mfCommonDefs.mk#L214). Removing the `INSTALL_PREFIX` variable here _may_ fail the RPM generation and/or the local installation when using the system-wide sysroot. One solution would be to split the sysroot tree and the staging tree which are intrinsically different.

Considering these issues, the RPM structures need to be also checked carefully.

**Comment by jsturdy** [comment]
I can almost guarantee that the RPM structure is correct.
The `make install` is executed during the RPM generation, and the location that the files are placed is what is packaged (hence the creation of the `/mnt/persistent/...`)
The local installation is only really expected to be used on the host, all other files created during this step are *only* used during RPM building (so if installing to `INSTALL_PREFIX` for development, one should likely only use the `make x86_64.install` target (though there shouldn't be any problem with the `/mnt/persistent/...` stuff existing).
The local filesystem extra (`AFS_HOME` in your case) I'm not actually sure, I probably haven't noticed that, though what is actually there?

If you've actually encountered an issue when using the local installation and developing against that, please report that, otherwise I don't consider this a bug, or even medium priority

**Comment by lpetre-ulb** [comment]
> I can almost guarantee that the RPM structure is correct.

Indeed, it is. :)

> The `make install` is executed during the RPM generation, and the location that the files are placed is what is packaged (hence the creation of the `/mnt/persistent/...`)
> The local installation is only really expected to be used on the host, all other files created during this step are _only_ used during RPM building (so if installing to `INSTALL_PREFIX` for development, one should likely only use the `make x86_64.install` target (though there shouldn't be any problem with the `/mnt/persistent/...` stuff existing).

It would be a mess to create files for the targeted board on the host (I don't expect `/mnt/persistent` to be stuffed with anything). Moreover, the installation path on the ATCA cards, might be common with the host.

If I run `make install`, with or without `INSTALL_PREFIX`, I expect the right thing to be automatically be done, i.e., only the host files being installed. It is terribly cumbersome to have to use `make x86_64.install` for something which could be done automatically.

> The local filesystem extra (`AFS_HOME` in your case) I'm not actually sure, I probably haven't noticed that, though what is actually there?

Everything which should be installed in the Peta stage (libraries and headers files) is installed into this directory. Actually, the full path is `${INTSALL_PREFIX}/${PETA_STAGE}` and `${PETA_STAGE}` is `${INSTALL_PREFIX}/opt/gem-peta-stage`. So the path is "right", but is not what I expected, does not in all situations and probably does not work with the other repositories Makefiles (although, admittedly, I haven't tested that).

This is where the difference between `PREFIX` and `DESTDIR` becomes really important. ;)

> If you've actually encountered an issue when using the local installation and developing against that, please report that, otherwise I don't consider this a bug, or even medium priority

I consider this issue as a bug and this is why I opened it. I wanted to debug the templated RPC calls (which require changes in more than one repository), but I couldn't because of this very same issue.

**Comment by jsturdy** [comment]
> I consider this issue as a bug and this is why I opened it. I wanted to debug the templated RPC calls (which require changes in more than one repository), but I couldn't because of this very same issue.

So far I haven't seen any evidence of a bug..., i.e., something that actually fails when you perform some set of steps including a `INSTALL_PREFIX=/tmp/development-area make install` for `xhal` (and others you're manually building) and then try to build `ctp7_modules`?

This is not to say that `make install` is doing the "correct" thing, only that it is doing a **sufficient** thing (indeed, the target itself was **only** added to provide a simple way for locally developing against non-system installed packages, rather than creating a "proper" installation).
If the local installation is not doing a **sufficient** thing, then I would consider this a bug, otherwise I consider it a "feature" (bad though it may smell)

That being said, I **do** expect that the host part of the resulting `make install` to be fully functional from both a compile time dependency point of view, as well as a runtime testing point of view (provided properly set paths...)

**Comment by lpetre-ulb** [comment]
> > I consider this issue as a bug and this is why I opened it. I wanted to debug the templated RPC calls (which require changes in more than one repository), but I couldn't because of this very same issue.
> 
> So far I haven't seen any evidence of a bug..., i.e., something that actually fails when you perform some set of steps including a `INSTALL_PREFIX=/tmp/development-area make install` for `xhal` (and others you're manually building) and then try to build `ctp7_modules`?

Ok, fine, I'll try to come up with a complete minimal (non-)working example this week.

> This is not to say that `make install` is doing the "correct" thing, only that it is doing a **sufficient** thing (indeed, the target itself was **only** added to provide a simple way for locally developing against non-system installed packages, rather than creating a "proper" installation).
> If the local installation is not doing a **sufficient** thing, then I would consider this a bug, otherwise I consider it a "feature" (bad though it may smell)

I've never seen any build system in which the installation target is unable to perform a proper installation (local or system-wide shouldn't matter). One of the consequences would be the inability to create an RPM package "the right way" (i.e. a RHEL, Fedora, SUSE and CentOS do).

> That being said, I **do** expect that the host part of the resulting `make install` to be fully functional from both a compile time dependency point of view, as well as a runtime testing point of view (provided properly set paths...)

Actually, I'm not interested in the host part; this one is "easy" to do and to check. I'm particularly interested in the cross-compilation part which is both tricky and harder to test.

**Comment by jsturdy** [comment]
> Ok, fine, I'll try to come up with a complete minimal (non-)working example this week.

At the present time, this is really non-critical.

> Actually, I'm not interested in the host part; this one is "easy" to do and to check. I'm particularly interested in the cross-compilation part which is both tricky and harder to test.

Sure, but as you (possibly) confirmed above, the generated RPMs are correct (one could simply try to install the arm RPMs onto a CTP7...)
However, in the interest actually testing the code, whether the packaging for arm is actually done correctly, is secondary (at the present time), one can simply proceed as we've done for the past 3 years; manually put the CTP7 libraries on the card where they are "expected" (this *should* match the arm RPM structure, but it hasn't been extensively tested, and there may yet be some things needing to be ironed out

**Comment by lpetre-ulb** [comment]
@jsturdy, I didn't manage to install `xHAL` in location environment with the procedure we discussed after the SW developers meeting. That's is export the `PETA_STAGE`, but set the `INSTALL_PREFIX` only for the installation target.

However, I did manage to install everything in what seems to be the right way when setting the variables only when are needed (i.e. `PETA_STAGE` during build and `INSTALL_PREFIX` during installation):

``` bash
$ scl enable devtoolset-8 -- make -j8 PETA_PATH=/afs/cern.ch/user/l/lpetre/GEM/develop/local_install/opt/gem-peta-stage
$ scl enable devtoolset-8 -- make install INSTALL_PREFIX=/afs/cern.ch/user/l/lpetre/GEM/develop/local_install
```

However, this is not very practical because one needs to set the variables for command invocation. Moreover, it is impossible to combine the two commands in one since the set of variables must be different.

I'm going to attempt to build (and fix) everything related to the templated RPC this week and see how well it goes.

**Comment by jsturdy** [comment]
Here's what I did on the VM just now (clean env, but just realized that I'm never touching `PETA_PATH`, only modifying `PETA_STAGE` with an export, as needed, so I haven't fully abstracted the potential different target boards that may one day exist :-():

```
[gembuild@gemdaq-build-xdaq15 ~]$ git clone --recurse-submodules https://github.com/cms-gem-daq-project/reedmuller-c.git
Cloning into 'reedmuller-c'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 152 (delta 4), reused 8 (delta 2), pack-reused 140
Receiving objects: 100% (152/152), 220.13 KiB | 748.00 KiB/s, done.
Resolving deltas: 100% (78/78), done.
Submodule 'config' (git@github.com:cms-gem-daq-project/gembuild.git) registered for path 'config'
Cloning into '/home/gembuild/reedmuller-c/config'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:cms-gem-daq-project/gembuild.git' into submodule path '/home/gembuild/reedmuller-c/config' failed
Failed to clone 'config'. Retry scheduled
Cloning into '/home/gembuild/reedmuller-c/config'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:cms-gem-daq-project/gembuild.git' into submodule path '/home/gembuild/reedmuller-c/config' failed
Failed to clone 'config' a second time, aborting
[gembuild@gemdaq-build-xdaq15 ~]$ git clone --recurse-submodules -b feature/templated-rpc-methods https://github.com/cms-gem-daq-project/xhal.git
Cloning into 'xhal'...
remote: Enumerating objects: 393, done.
remote: Counting objects: 100% (393/393), done.
remote: Compressing objects: 100% (217/217), done.
remote: Total 7992 (delta 174), reused 371 (delta 158), pack-reused 7599
Receiving objects: 100% (7992/7992), 16.94 MiB | 12.75 MiB/s, done.
Resolving deltas: 100% (4426/4426), done.
Submodule 'config' (https://github.com/cms-gem-daq-project/gembuild.git) registered for path 'config'
Cloning into '/home/gembuild/xhal/config'...
remote: Enumerating objects: 141, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 406 (delta 88), reused 88 (delta 42), pack-reused 265
Receiving objects: 100% (406/406), 135.60 KiB | 704.00 KiB/s, done.
Resolving deltas: 100% (256/256), done.
Submodule path 'config': checked out '30f5327e456c26b23a1f6ec224889c5c46610226'
[gembuild@gemdaq-build-xdaq15 ~]$ cd reedmuller-c/
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ emacs -nw .gitmodules
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ git submodule sync
Synchronizing submodule url for 'config'
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ git submodule update --init --recursive
Cloning into '/home/gembuild/reedmuller-c/config'...
Submodule path 'config': checked out '30f5327e456c26b23a1f6ec224889c5c46610226'
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ export PATH=/opt/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/bin:$PATH
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ mkdir -p /tmp/gembuild/gemos-release-build/opt/gem-peta-stage/ctp7/
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ ln -ns /opt/gem-peta-stage/ctp7/lib /tmp/gembuild/gemos-release-build/opt/gem-peta-stage/ctp7/
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ ln -ns /opt/gem-peta-stage/ctp7/usr /tmp/gembuild/gemos-release-build/opt/gem-peta-stage/ctp7/
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ ll /tmp/gembuild/gemos-release-build/
total 0
drwxr-xr-x. 3 gembuild gembuild 28 Mar  4 10:57 opt
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ tree /tmp/gembuild/gemos-release-build/
/tmp/gembuild/gemos-release-build/
└── opt
    └── gem-peta-stage
        └── ctp7
            ├── lib -> /opt/gem-peta-stage/ctp7/lib
            └── usr -> /opt/gem-peta-stage/ctp7/usr

5 directories, 0 files
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ export PETA_STAGE=/tmp/gembuild/gemos-release-build/opt/gem-peta-stage/ctp7
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ INSTALL_PREFIX=/tmp/gembuild/gemos-release-build make install
[snip]
[gembuild@gemdaq-build-xdaq15 reedmuller-c]$ cd ../xhal
[gembuild@gemdaq-build-xdaq15 xhal]$ . /opt/rh/devtoolset-8/enable
[gembuild@gemdaq-build-xdaq15 xhal]$ INSTALL_PREFIX=/tmp/gembuild/gemos-release-build make install
[snip]
```
and this is the tree I get:
```
[gembuild@gemdaq-build-xdaq15 xhal]$ tree /tmp/gembuild/gemos-release-build/
/tmp/gembuild/gemos-release-build/
├── mnt
│   └── persistent
│       ├── reedmuller
│       │   ├── bin
│       │   │   ├── rmdecode
│       │   │   └── rmencode
│       │   ├── etc
│       │   ├── include
│       │   │   ├── combination.h
│       │   │   ├── common.h
│       │   │   ├── ksubset.h
│       │   │   ├── matrix.h
│       │   │   ├── reedmuller.h
│       │   │   └── vector.h
│       │   ├── lib
│       │   │   ├── libreedmuller.so -> libreedmuller.so.0.0
│       │   │   ├── libreedmuller.so.0.0 -> libreedmuller.so.0.0.0
│       │   │   └── libreedmuller.so.0.0.0
│       │   └── scripts
│       └── xhal
│           ├── bin
│           ├── etc
│           ├── include
│           │   ├── packageinfo.h
│           │   └── xhal
│           │       ├── client
│           │       │   ├── rpcman
│           │       │   │   ├── calibration_routines.h
│           │       │   │   ├── daq_monitor.h
│           │       │   │   ├── optohybrid.h
│           │       │   │   ├── utils.h
│           │       │   │   └── vfat3.h
│           │       │   ├── utils
│           │       │   │   └── PyTypes.h
│           │       │   ├── XHALDevice.h
│           │       │   └── XHALInterface.h
│           │       ├── common
│           │       │   ├── rpc
│           │       │   │   ├── call.h
│           │       │   │   ├── common.h
│           │       │   │   ├── compat.h
│           │       │   │   ├── exceptions.h
│           │       │   │   ├── helper.h
│           │       │   │   └── register.h
│           │       │   └── utils
│           │       │       ├── Exception.h
│           │       │       ├── XHALXMLNode.h
│           │       │       └── XHALXMLParser.h
│           │       ├── extern
│           │       │   ├── lmdb++.h
│           │       │   ├── ModuleManager.h
│           │       │   ├── wiscRPCMsg.h
│           │       │   └── wiscrpcsvc.h
│           │       └── server
│           │           └── LMDB.h
│           ├── lib
│           │   ├── libxhal-base.so -> libxhal-base.so.3.2
│           │   ├── libxhal-base.so.3.2 -> libxhal-base.so.3.2.2
│           │   ├── libxhal-base.so.3.2.2
│           │   ├── libxhal-server.so -> libxhal-server.so.3.2
│           │   ├── libxhal-server.so.3.2 -> libxhal-server.so.3.2.2
│           │   └── libxhal-server.so.3.2.2
│           └── scripts
├── opt
│   ├── gem-peta-stage
│   │   └── ctp7
│   │       ├── lib -> /opt/gem-peta-stage/ctp7/lib
│   │       ├── mnt
│   │       │   └── persistent
│   │       │       ├── reedmuller
│   │       │       │   └── lib
│   │       │       │       ├── libreedmuller.so -> libreedmuller.so.0.0
│   │       │       │       ├── libreedmuller.so.0.0 -> libreedmuller.so.0.0.0
│   │       │       │       └── libreedmuller.so.0.0.0
│   │       │       └── xhal
│   │       │           └── lib
│   │       │               ├── libxhal-base.so -> libxhal-base.so.3.2
│   │       │               ├── libxhal-base.so.3.2 -> libxhal-base.so.3.2.2
│   │       │               ├── libxhal-base.so.3.2.2
│   │       │               ├── libxhal-server.so -> libxhal-server.so.3.2
│   │       │               ├── libxhal-server.so.3.2 -> libxhal-server.so.3.2.2
│   │       │               └── libxhal-server.so.3.2.2
│   │       └── usr -> /opt/gem-peta-stage/ctp7/usr
│   ├── reedmuller
│   │   ├── bin
│   │   │   ├── rmdecode
│   │   │   └── rmencode
│   │   ├── etc
│   │   ├── include
│   │   │   ├── combination.h
│   │   │   ├── common.h
│   │   │   ├── ksubset.h
│   │   │   ├── matrix.h
│   │   │   ├── reedmuller.h
│   │   │   └── vector.h
│   │   ├── lib
│   │   │   ├── libreedmuller.so -> libreedmuller.so.0.0
│   │   │   ├── libreedmuller.so.0.0 -> libreedmuller.so.0.0.0
│   │   │   └── libreedmuller.so.0.0.0
│   │   └── scripts
│   └── xhal
│       ├── bin
│       │   └── reg_interface_gem
│       │       └── gem_reg.py
│       ├── etc
│       ├── include
│       │   ├── packageinfo.h
│       │   └── xhal
│       │       ├── client
│       │       │   ├── rpcman
│       │       │   │   ├── calibration_routines.h
│       │       │   │   ├── daq_monitor.h
│       │       │   │   ├── optohybrid.h
│       │       │   │   ├── utils.h
│       │       │   │   └── vfat3.h
│       │       │   ├── utils
│       │       │   │   └── PyTypes.h
│       │       │   ├── XHALDevice.h
│       │       │   └── XHALInterface.h
│       │       ├── common
│       │       │   ├── rpc
│       │       │   │   ├── call.h
│       │       │   │   ├── common.h
│       │       │   │   ├── compat.h
│       │       │   │   ├── exceptions.h
│       │       │   │   ├── helper.h
│       │       │   │   └── register.h
│       │       │   └── utils
│       │       │       ├── Exception.h
│       │       │       ├── XHALXMLNode.h
│       │       │       └── XHALXMLParser.h
│       │       ├── extern
│       │       │   ├── lmdb++.h
│       │       │   ├── ModuleManager.h
│       │       │   ├── wiscRPCMsg.h
│       │       │   └── wiscrpcsvc.h
│       │       └── server
│       │           └── LMDB.h
│       ├── lib
│       │   ├── libxhal-base.so -> libxhal-base.so.3.2
│       │   ├── libxhal-base.so.3.2 -> libxhal-base.so.3.2.2
│       │   ├── libxhal-base.so.3.2.2
│       │   ├── libxhal-client.so -> libxhal-client.so.3.2
│       │   ├── libxhal-client.so.3.2 -> libxhal-client.so.3.2.2
│       │   ├── libxhal-client.so.3.2.2
│       │   ├── libxhal-rpcman.so -> libxhal-rpcman.so.3.2
│       │   ├── libxhal-rpcman.so.3.2 -> libxhal-rpcman.so.3.2.2
│       │   ├── libxhal-rpcman.so.3.2.2
│       │   ├── libxhal-server.so -> libxhal-server.so.3.2
│       │   ├── libxhal-server.so.3.2 -> libxhal-server.so.3.2.2
│       │   ├── libxhal-server.so.3.2.2
│       │   ├── xhalpy.so -> xhalpy.so.3.2
│       │   ├── xhalpy.so.3.2 -> xhalpy.so.3.2.2
│       │   └── xhalpy.so.3.2.2
│       └── scripts
└── usr
    ├── lib
    │   ├── debug
    │   │   ├── mnt
    │   │   │   └── persistent
    │   │   │       ├── reedmuller
    │   │   │       │   ├── bin
    │   │   │       │   └── lib
    │   │   │       └── xhal
    │   │   │           ├── bin
    │   │   │           └── lib
    │   │   └── opt
    │   │       ├── reedmuller
    │   │       │   ├── bin
    │   │       │   └── lib
    │   │       └── xhal
    │   │           ├── bin
    │   │           └── lib
    │   └── python2.7
    │       └── site-packages
    │           └── xhal
    │               ├── __init__.py
    │               └── reg_interface_gem
    │                   ├── core
    │                   │   ├── __init__.py
    │                   │   ├── ri_prompt_extended.py
    │                   │   └── vfat_config.py
    │                   ├── __init__.py
    │                   ├── MANIFEST.in
    │                   ├── README.md
    │                   ├── reg_interface_gem.prep
    │                   └── requirements.txt
    └── src
        └── debug
            ├── reedmuller-0.0.0
            │   └── src
            │       ├── combination.c
            │       ├── ksubset.c
            │       ├── matrix.c
            │       ├── reedmuller.c
            │       ├── rmdecode.c
            │       ├── rmencode.c
            │       └── vector.c
            └── xhal-3.2.2
                └── src
                    ├── client
                    │   ├── python_wrappers
                    │   │   └── XHALInterface_python.cpp
                    │   ├── rpc_manager
                    │   │   ├── calibration_routines.cpp
                    │   │   ├── daq_monitor.cpp
                    │   │   ├── optohybrid.cpp
                    │   │   ├── utils.cpp
                    │   │   └── vfat3.cpp
                    │   ├── XHALDevice.cpp
                    │   └── XHALInterface.cpp
                    ├── common
                    │   ├── rpc
                    │   │   └── exceptions.cpp
                    │   └── utils
                    │       └── XHALXMLParser.cpp
                    └── server
                        └── LMDB.cpp

92 directories, 126 files
```

**Comment by lpetre-ulb** [comment]
> Here's what I did on the VM just now (clean env, but just realized that I'm never touching `PETA_PATH`, only modifying `PETA_STAGE` with an export, as needed, so I haven't fully abstracted the potential different target boards that may one day exist :-():

Okay, so the current build system is only a partial solution. :-(

**Comment by lpetre-ulb** [comment]
Simplified and fixed in the new repository.
