### ISSUE TITLE
[reedmuller-c] Host reedmuller-c in the cms-gem-daq-project organization

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/xhal#142]
(Cannot open an issue in the right repository because the functionnality is disabled by default for forks.)

## Brief summary of issue

Currently, the only GEM compatible `reedmuller-c` release in hosted in a personal GitHub repository, [`jsturdy/reedmuller-c`](https://github.com/jsturdy/reedmuller-c).

A small inconvenience is that issues cannot currently be created in this repository.

Moe importantly, as any other GEM online software related library, it should be owned by the `cms-gem-daq-project` organization. This is particularly true since that specific library release is mandatory to compile the RPC modules.

### Types of issue

- [x] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

`reedmuller-c` should be hosted in the `cms-gem-daq-project` GitHub organization.

## Current Behavior

`reedmuller-c` is hosted in a personal GitHub repository.

## Possible Solution (for bugs)

Transfer the ownership of [`jsturdy/reedmuller-c`](https://github.com/jsturdy/reedmuller-c) to the [`cms-gem-daq-project` organization](https://github.com/cms-gem-daq-project).

## Context (for feature requests)

Architecture/infrastructure clean up.

**Comment by jsturdy** [comment]
Done (or at least in progress)

**Comment by lpetre-ulb** [comment]
> Done (or at least in progress)

Thank you!
