### ISSUE TITLE
Discussion: results array in genScan(...) and thresholdScan(...) is a local variable and may prove troublesome

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#16]
## Brief summary of issue

I believe the current implementation of RPC methods `genScan(...)` and `thresholdScan(...)` will be more difficult to integrate with our existing repositories and use and cause unnecessary file I/O operations.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)
- [X] Discussion

## Expected Behavior

The two scan applications [genScan(...)](https://github.com/cms-gem-daq-project/xhal/blob/447afc45fcac5670cd69bff9e82b350a321aaeb7/src/common/rpc_manager/calibration_routines.cc#L28) and [thresholdScan(...)](https://github.com/cms-gem-daq-project/xhal/blob/447afc45fcac5670cd69bff9e82b350a321aaeb7/src/common/rpc_standalone_client/rwreg.cpp#L93) should allow for a pointer of the `results` array to be supplied as an input argument rather than be a local variable.  

This should allow an array in python to be passed with the library is called and then the scan data is stored in the array.  Then integration with the current scan tools (and subsequent analysis) would be seamless, e.g.:

```
if v3El:
    genScan(scanData, ....)
else:
    scanData = getUltraScanResults(ohboard, options.gtx, THRESH_MAX - THRESH_MIN + 1, options.debug)
```

Then scanData can be parsed accordingly inside the ultra scan script and be neatly stored into the current output `TTree`.

I think this will offer a more seamless integration with the current `vfatqc-python-scripts`.   As shown in my original PR: https://github.com/cms-gem-daq-project/xhal/pull/13/files. From [scanDAC](https://github.com/bdorney/xhal/blob/0df591e8449c2f7d8c3fea08ee0a01ae26b11415/src/common/rpc_standalone_client/rwreg.cpp#L494) of my original PR:

```
DLLEXPORT uint32_t scanDAC(uint32_t* result, ssize_t size,
        unsigned int ohN, unsigned int vfatMask, unsigned int chan, std::string scanReg,
        unsigned int nEvts, unsigned int scanMin, unsigned int scanMax, unsigned int stepSize){
    req = wisc::RPCMsg("calibration_routines.genScan");
    req.set_word("ohN",ohN);
    req.set_word("mask",vfatMask);
    req.set_word("ch",chan);
    req.set_word("scanReg",scanReg);
    req.set_word("nevts",nEvts);
    req.set_word("dacMin",scanMin);
    req.set_word("dacMax",scanMax);
    req.set_word("dacStep",stepSize);


    try{
        rsp = rpc.call_method(req);
    }
    STANDARD_CATCH;


    try{
	    if (rsp.get_key_exists("error")) {
            printf("Error: %s",rsp.get_string("error").c_str());
            return 1;
        }
        else {
	        ASSERT(rsp.get_word_array_size("data") == size);
            rsp.get_word_array("data", result);
        }
    }
	STANDARD_CATCH;


    return 0;
} //End scanDAC()
```

Here the `results` pointer is an input.

## Current Behavior

In PR https://github.com/cms-gem-daq-project/xhal/pull/15/files new scan functions were added:
- [genScan(...)](https://github.com/cms-gem-daq-project/xhal/blob/447afc45fcac5670cd69bff9e82b350a321aaeb7/src/common/rpc_manager/calibration_routines.cc#L28) 
- [thresholdScan(...)](https://github.com/cms-gem-daq-project/xhal/blob/447afc45fcac5670cd69bff9e82b350a321aaeb7/src/common/rpc_standalone_client/rwreg.cpp#L93)

However in these functions `uint32_t* result` is a local variable.  I think this will makes integration with `vfatqc-python-scripts` very challenging.  Right now ultra scan results are expecting a return value, take `vfatqc-python-scripts/ultraThreshold.py`:

```
            scanData = getUltraScanResults(ohboard, options.gtx, THRESH_MAX - THRESH_MIN + 1, options.debug)
            sys.stdout.flush()
            for i in range(0,24):
            	if (mask >> i) & 0x1: continue
                vfatN[0] = i
                dataNow      = scanData[i]
                trimRange[0] = (0x07 & readVFAT(ohboard,options.gtx, i,"ContReg3"))
                for VC in range(THRESH_MAX-THRESH_MIN+1):
                    vth1[0]  = int((dataNow[VC] & 0xff000000) >> 24)
                    vth[0]   = vth2[0] - vth1[0]
                    Nhits[0] = int(dataNow[VC] & 0xffffff)
                    myT.Fill()
                    pass
                pass
            myT.AutoSave("SaveSelf")
            pass
```

Here `scanData` is obtained at each iteration of the loop over all channels.  

However, [genScan(...)](https://github.com/cms-gem-daq-project/xhal/blob/447afc45fcac5670cd69bff9e82b350a321aaeb7/src/common/rpc_manager/calibration_routines.cc#L28) and [thresholdScan(...)](https://github.com/cms-gem-daq-project/xhal/blob/447afc45fcac5670cd69bff9e82b350a321aaeb7/src/common/rpc_standalone_client/rwreg.cpp#L93) open an output text file and write the data for the (`vfat`,`ch`) pair to it.  This implies that to scan over all channels 128 sets of file I/O operations will need to be done and seems a bit excessive.  Additionally trying to organize and use this data in the `gem-plotting-tools/` is not straight forward.

I think we can strive for a more seamless integration with lower changes.

## Context (for feature requests)

The current implementation does not allow for direct access of the scan results inside a scan application and instead causes ~128 sets of file I/O operations.  

I'd like to open a discussion on the advantages/disadvantages and the long term strategy of this.

**Comment by mexanick** [comment]
This is fair point. I can do it. Just need a clarification in which order scanData from VFAT2 is containing the information.

**Comment by bdorney** [comment]
> This is fair point. I can do it. Just need a clarification in which order scanData from VFAT2 is containing the information.

@mexanick 

For `ultraScurve.py` the information goes: `CHAN_MIN` -> `CHAN_MAX`.  For each `chan` there is a nested loop which goes `VFAT0` -> `VFAT24`.  See [L143](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/8879e27389917ef2273965b4ed7f1951506e97e2/ultraScurve.py#L143) of `ultraScurve.py`.

The situation is the same is for [ultraThreshold.py](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/8879e27389917ef2273965b4ed7f1951506e97e2/ultraThreshold.py#L101).

For `trimChamber.py` it just calls `ultraScurve.py` so no worries there.  And the latency tools do not store information at channel level.
