### ISSUE TITLE
Feature Request: setup.sh sets correct computing environment for compilation

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#17]
## Brief summary of issue

Based on format of other repositories would expect:

```
cd $BUILD_HOME/xhal
source setup.sh
make
```

To compile the repository and correctly create the required shared libraries.  However when attempting obtain the following error message when calling `make`:

```
% make
g++ -O0 -g3 -fno-inline -Wall -fPIC -pthread -m64 -std=gnu++14 -I/opt/xdaq/include -I/opt/rh/devtoolset-6/root/usr/include -I/afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/xhal/xhal/include -L/opt/xdaq/lib -L/afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/xhal/xhal/lib/x86_64 -llog4cplus -lxerces-c  -c -o src/common/utils/XHALXMLParser.o src/common/utils/XHALXMLParser.cpp
cc1plus: error: unrecognized command line option "-std=gnu++14"
make: *** [src/common/utils/XHALXMLParser.o] Error 1
```

Unclear which `g++` version should be used.  Based on [this link](https://gcc.gnu.org/projects/cxx-status.html#cxx14) it should be either v4.9 or v5.X.

Request that `setup.sh` correctly configures this by default, and anything else that would required to successfully compile.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

Able to compile the repo after calling `setup.sh`

## Current Behavior

Cannot compile the repo.

## Context (for feature requests)

Would be helpful when debugging/testing/developing python based scan applications for v3 electronics if we could compile xhal and make tweaks as needed (which would result in new PR's).

## Your Environment

* Version used: b7f18121301e038a0124dabb1ab339ee4891986e
* Shell used: `/bin/zsh`

**Comment by mexanick** [comment]
Adding required compilers to the $PATH is a responsibility of either PC administrator or a developer him(her)self. This is specific to the PC where you are going to compile, so can't be made a part of the repository
