### ISSUE TITLE
Specification of hardware to connect to 

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#19]
## Brief summary of issue
When the tools take an argument to connect to some hardware, they should be able to take **any** hostname that will work, as such the current implementation of the `sca.py` parsing does not pass this bar, as it assumes an `eagleXY` connection

**Comment by jsturdy** [comment]
@mexanick, I have to look at my current version and see if it is sufficient, if so, I'll push and issue a PR

**Comment by mexanick** [comment]
This line suggests any hostname should be alright:
https://github.com/cms-gem-daq-project/xhal/blob/14c87ee2fc7507e586ce2b45bdd69985ff560887/python/reg_interface/sca.py#L71
