### ISSUE TITLE
Change setup.sh to not be path dependent

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#25]
## Brief summary of issue

Right now `setup.sh` is dependent on the file path, e.g. you need to:

```
cd $BUILD_HOME/xhal
source setup.sh
```

Suggest to change [L1](https://github.com/cms-gem-daq-project/xhal/blob/c9a76359abda4a7b73a30f2be3f86b94e1a2a084/setup.sh#L1) too:

```
#export XHAL_ROOT=<your path>/xhal
if [[ -n "$XHAL_ROOT" ]]; then
    echo XHAL_ROOT $XHAL_ROOT
else
    echo "XHAL_ROOT not set, please set XHAL_ROOT to the directory above the root of your repository"
    echo "(export XHAL_ROOT=<your path>/xhal) and then rerun this script"
    return
fi
```

This will require the user to setup `$XHAL_ROOT` themselves but will make the script location independent and conform to the other setup scripts in our project.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

**Comment by mexanick** [comment]
This issue was almost fixed in https://github.com/cms-gem-daq-project/xhal/pull/35
However a problem has been discovered when working with `scl *** enable bash`
@jsturdy is looking to fix it
