### ISSUE TITLE
Standardization of release naming

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#27]
In setting up scripts capable of being able to set up a CTP7 using a specific release, it came up that the release tagging is not consistent.  A list of recent releases is:
* `2.1.0`
* `v2.0.0`
* `v1.0.0`

The workaround is that the user will have to specify `v2.0.0` or `2.1.0`, but ideally, the user would specify only `x.y.z` and the `v` (if part of the semantic versioning) would be handled by the script

**Comment by mexanick** [comment]
resolved: all the names now vX.Y.Z
