### ISSUE TITLE
Function to write same register on all/multiple OptoHybrid links in reg_interface.py

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#3]
It would be nice to have a function that offers the possibility to "broadcast" a write to all/some OptoHybrids

**Comment by mexanick** [comment]
New method added:
        """ Begin command by selecting OHs, followed by command. 
USAGE: broadcastOH _OH_numbers_ _command_ _register_ _value_
            OH numbers can be separated by comma or include range: 0,2-5 NO SPACES SHOULD BE BETWEEN!!
            command can be either read or write and should follow by OH register name (see example below). If command is write, add the value to write at the end
            EXAMPLE:
            `broadcastOH 0,2-5 read CONTROL.CLOCK.REF_CLK`
            OR
            `broadcastOH 0,2-5 write CONTROL.CLOCK.REF_CLK 0x1`
        """
