### ISSUE TITLE
Printing of some error messages corrupts output readability

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#4]
Using ```reg_interface.py``` from the ```CTP7``` when an optical link is not connected results in a ```Bus Error```, which prompts a message ```memHandle NULL, open it```, this second message prints only on the output of the second command.
This message should not be printed to the screen, and if it needs to be logged, should be put into an error/logfile.
Using the ```reg_interface.py``` from the host machine this seems to not be the case, but should be verified.

**Comment by mexanick** [comment]
It looks to me that you've mixed up usage from host machine vs usage from CTP7. 
At least that's what I observe by running the code as well as looking in the source. This message is a kind of debug remnant so I just suppressed it (however if there'll be real error with memory service, which is very rare, the code will print out the error message and return).
Fixed code pushed to the github in the branch development and updated library (librwreg_ctp7.so) is loaded to eagle34 (904) card. Other cards will be updated later, as well as new release will be published (I'm going to add some more fixes)
