### ISSUE TITLE
Feature Request: reg_interface.py executable

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#41]
## Brief summary of issue

`$XHAL_ROOT/python/reg_interface/` is part of `$PATH` however `reg_interface.py` is not executable.  Quality of life feature, request it to be executable. 

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

Not needing to go to `$XHAL_ROOT/python/reg_interface/` and execute `python reg_interface.py` and instead just type `reg_interface.py` from anywhere.

## Current Behavior

See above comment.

## Context (for feature requests)

Quality of live feature

## Your Environment

* Version used: `develop`
* Shell used: `/bin/zsh`

**Comment by jsturdy** [comment]
Has slipped from patches in the past, including now

**Comment by jsturdy** [comment]
Fixed by #42
