### ISSUE TITLE
Write rights to the repo

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/xhal#8]
@jsturdy , it looks like I don't have the write right for this repo and thus can't merge PR. 
Could you please fix this ( I think this happened when I transferred ownership...)?

**Comment by jsturdy** [comment]
Oops!  Should be sorted now, give it a check?
I'll run my tag creator script so the tags are standardized wrt the other repos

**Comment by mexanick** [comment]
yep, it works now! Don't know what went wrong... I think I transferred ownership in the same way as for the ctp7_modules, but there I could merge with no problems and here not...
