### ISSUE TITLE
Put on C++ rails to integrate properly with the cmsgemos project

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/xhal#86]
## Brief summary of issue
Currently the library is written entirely in C-style with method exported to C-style DLLs via extern C. No classes or namespaces are used per se (however, the language is still C++ and certain parts are c++ code, like wisc::RPCSvc and wisc::RPCMsg). For the ease of use the library should be refactored to provide namespaces and classes. This can be implemented by writing a classes with all the current methods and provide `DLLEXPORT` wrappers around them for compatibility with python code, like
```
namespace a {
  class B {
  public:
    cpp_method(){printf("Hello World");}
  };
}
extern "C" c_method(a::B* b)
{
  b->cpp_method();
}
```

In this case it won't require major refactoring of python code using the xHAL. The other option (requiring more work) is to rewrite everything in regular C++ and use boost_python to provide python wrappers. However this will call upon changes in our python repositories as well. 

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Your Environment

* Version used:
* Shell used:

**Comment by jsturdy** [comment]
Personal preference for `C++` + `boost::python` exporting for basically identical interfaces, but let's start at the fundamental and see where we go from there...
FYI, the groundwork for this has already been started in `gempython`
